server {
    listen 80;
    server_name localhost;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate /etc/nginx/certs/server.crt;
    ssl_certificate_key /etc/nginx/certs/server.key;

    # FRASE ANTIFRAUDE: holaquetal
    add_header X-Antifraude "holaquetal" always;

    location /catalog/ {
        rewrite ^/catalog/(.*) /$1 break;
        proxy_pass http://catalog-api:8000;
        proxy_set_header Host $host;
    }

    location /orders/ {
        rewrite ^/orders/(.*) /$1 break;
        proxy_pass http://orders-api:8000;
        proxy_set_header Host $host;
    }

    location /customers/ {
        rewrite ^/customers/(.*) /$1 break;
        proxy_pass http://customers-api:8000;
        proxy_set_header Host $host;
    }
}
